(function (Q, $, window, undefined) {
/**
 * Media/presentation/player tool
 *
 * Plays back a recorded presentation from its transcript.vtt file.
 * Narrates cues and activates visualizations at NOTE boundaries.
 * Timing is rubato — each cue takes as long as the narration needs,
 * regardless of the original session's timing. Suitable for translated
 * narrations, slower/faster playback, or voice-cloned replays.
 *
 * NARRATION MODES (selected automatically per cue):
 *
 *   'audio'      Pre-generated mp3 file exists at audioBaseUrl/cue-{ordinal}.mp3
 *                Q.Audio.load() preloads it; Q.Audio.play() plays it.
 *                Generated by the AI plugin TTS pipeline. Enables voice cloning.
 *                Falls back to 'speak' if file is missing or ordinal unknown.
 *
 *   'speak'      Q.Audio.speak(text, options) — wraps window.speechSynthesis
 *                and any native TTS available. Zero latency, no API key.
 *                Always available as fallback.
 *
 * The first NOTE in the VTT (session_start) contains the session origin timestamp.
 * All other timing is derived from narration duration — no hard timestamps used.
 *
 * @module Media
 * @class Media/presentation/player
 */
Q.Tool.define('Media/presentation/player', function (options) {
    var tool  = this;
    var state = tool.state;

    state._cues    = [];   // { start, end, text, speaker, ordinal, index }
    state._notes   = [];   // { type, ordinal, ts, data, afterCueIndex, _applied }
    state._cursor  = 0;
    state._playing = false;
    state._stopped = false;

    tool._buildUI();

    if (state.vttUrl) {
        tool._loadVtt(state.vttUrl);
    } else if (state.publisherId && state.streamName) {
        tool._resolveVttUrl(function (url) { tool._loadVtt(url); });
    }

}, {
    publisherId:    null,
    streamName:     null,
    vttUrl:         null,
    lang:           'en-US',
    rate:           1,
    gender:         'female',   // 'female' | 'male' — used by Q.Audio.speak voice selection
    voice:          null,       // unused (Q.Audio.speak uses gender + locale)
    autoPlay:       false,
    showCaptions:   true,
    presentationEl: null,       // presentation tool element to control
    audioBaseUrl:   null,       // base URL for pre-generated cue audio files
                                // e.g. '/Q/uploads/Streams/yve/ael/ev/…'
}, {

    // ── UI ───────────────────────────────────────────────────────────────

    _buildUI: function () {
        var tool = this, state = tool.state;

        tool.element.style.setProperty('--AI-bg',     '#1a1d24');
        tool.element.style.setProperty('--AI-accent', '#5b8ef0');
        tool.element.style.setProperty('--AI-text',   '#f0eee8');
        tool.element.style.setProperty('--AI-sub',    '#9a9daa');

        tool.element.innerHTML =
            '<div style="font-family:system-ui;background:var(--AI-bg);border-radius:12px;'
          + 'padding:1.25rem 1.5rem;border:1px solid rgba(255,255,255,0.08)">'
          +   '<div class="Mpp_caption" style="min-height:2.5rem;color:var(--AI-text);'
          +   'font-size:1.05rem;line-height:1.6;margin-bottom:1rem;font-style:italic;'
          +   'opacity:.7">Loading…</div>'
          +   '<div style="display:flex;gap:.75rem;align-items:center;flex-wrap:wrap">'
          +     '<button class="Mpp_play" style="padding:.5rem 1.25rem;border-radius:999px;'
          +     'background:var(--AI-accent);color:#fff;border:none;cursor:pointer;'
          +     'font-size:.9rem;font-weight:600">▶ Play</button>'
          +     '<button class="Mpp_stop" style="padding:.5rem 1rem;border-radius:999px;'
          +     'background:rgba(255,255,255,0.08);color:var(--AI-text);border:none;'
          +     'cursor:pointer;font-size:.9rem">■ Stop</button>'
          +     '<select class="Mpp_rate" style="background:rgba(255,255,255,0.08);'
          +     'color:var(--AI-text);border:none;border-radius:6px;padding:.3rem .5rem;'
          +     'font-size:.85rem;cursor:pointer">'
          +       '<option value="0.75">0.75×</option>'
          +       '<option value="1" selected>1×</option>'
          +       '<option value="1.25">1.25×</option>'
          +       '<option value="1.5">1.5×</option>'
          +       '<option value="2">2×</option>'
          +     '</select>'
          +     '<span class="Mpp_prog" style="font-family:monospace;font-size:.8rem;'
          +     'color:var(--AI-sub)">— / —</span>'
          +   '</div>'
          + '</div>';

        var playBtn = tool.element.querySelector('.Mpp_play');
        var stopBtn = tool.element.querySelector('.Mpp_stop');
        var rateEl  = tool.element.querySelector('.Mpp_rate');

        playBtn.addEventListener('click', function () {
            if (state._playing) {
                tool.pause();
                playBtn.textContent = '▶ Play';
            } else {
                tool.play();
                playBtn.textContent = '⏸ Pause';
            }
        });
        stopBtn.addEventListener('click', function () {
            tool.stop();
            playBtn.textContent = '▶ Play';
        });
        rateEl.addEventListener('change', function () {
            state.rate = parseFloat(rateEl.value) || 1;
        });
    },

    // ── VTT loading and parsing ──────────────────────────────────────────

    _resolveVttUrl: function (callback) {
        var state = this.state;
        // Construct uploads path mirroring TranscriptEmitter._resolveTranscriptPath
        var splitId = state.publisherId.match(/.{1,3}/g).join('/');
        var base    = (Q.info && Q.info.baseUrl) || '';
        callback(base + '/Q/uploads/Streams/' + splitId
               + '/' + state.streamName + '/transcript.vtt');
    },

    _loadVtt: function (url) {
        var tool  = this;
        var state = tool.state;
        var cap   = tool.element.querySelector('.Mpp_caption');
        var prog  = tool.element.querySelector('.Mpp_prog');

        fetch(url)
            .then(function (r) {
                if (!r.ok) throw new Error('HTTP ' + r.status);
                return r.text();
            })
            .then(function (text) {
                tool._parseVtt(text);
                if (cap)  cap.textContent  = 'Ready — ' + state._cues.length + ' utterances';
                if (prog) prog.textContent = '0 / ' + state._cues.length;
                // Preload audio files for all cues that have ordinals
                if (state.audioBaseUrl) tool._preloadAudio();
                if (state.autoPlay) tool.play();
            })
            .catch(function (e) {
                if (cap) cap.textContent = 'Could not load transcript: ' + e.message;
            });
    },

    _parseVtt: function (text) {
        var state   = this.state;
        state._cues  = [];
        state._notes = [];
        var cueIndex = 0;

        text.split(/\n\n+/).forEach(function (block) {
            block = block.trim();
            if (!block || block === 'WEBVTT') return;

            if (block.indexOf('NOTE') === 0) {
                // One-line NOTE (our format): NOTE type [ordinal=N] [ts=N] {json}
                var line = block.replace(/^NOTE\s*/, '').split('\n')[0].trim();
                var note = _parseNoteLine(line, cueIndex);
                if (note) state._notes.push(note);
                return;
            }

            // Cue block
            var lines  = block.split('\n');
            var si     = (lines[0].indexOf('-->') < 0) ? 1 : 0; // skip optional id line
            if (!lines[si] || lines[si].indexOf('-->') < 0) return;

            var times = lines[si].split('-->');
            var start = _vttSec(times[0].trim());
            var end   = _vttSec(times[1].trim().split(' ')[0]);
            var raw   = lines.slice(si + 1).join(' ').trim();

            // Extract display name from <v Name>
            var speaker = '';
            var vm = raw.match(/<v ([^>]+)>/);
            if (vm) speaker = vm[1];

            // Extract ordinal from .ordinal-N class tag
            var ordinal = null;
            var om = raw.match(/\.ordinal-(\d+)/);
            if (om) ordinal = parseInt(om[1], 10);

            // Extract control flag — .control class marks voice commands
            // that drove the presentation (next slide, pin chart, etc.)
            // Player skips TTS for these — they were commands, not content.
            var isControl = raw.indexOf('.control') >= 0;

            // Plain text — strip all tags
            var plain = raw.replace(/<[^>]+>/g, '').trim();
            if (!plain) return;

            state._cues.push({
                start: start, end: end,
                text: plain, speaker: speaker,
                ordinal: ordinal, index: cueIndex,
                control: isControl
            });
            cueIndex++;
        });
    },

    // ── Audio preloading ─────────────────────────────────────────────────

    _preloadAudio: function () {
        var state = this.state;
        if (!state.audioBaseUrl || !Q.Audio || !Q.Audio.load) return;

        state._cues.forEach(function (cue) {
            if (cue.ordinal == null) return;
            var url = state.audioBaseUrl + '/cue-' + cue.ordinal + '.mp3';
            // Q.Audio.load(url, handler) — handler called when canPlayThrough
            // Stores instance in Q.Audio.collection[url]
            Q.Audio.load(url, function () {});
        });
    },

    // ── Playback ─────────────────────────────────────────────────────────

    play: function () {
        var state = this.state;
        if (state._playing) return;
        state._playing = true;
        state._stopped = false;
        this._playFrom(state._cursor);
    },

    pause: function () {
        var state = this.state;
        state._playing = false;
        // Q.Audio.stopSpeaking cancels speechSynthesis.
        // For pregenerated audio, pause the active Q.Audio instance if any.
        if (Q.Audio) {
            Q.Audio.stopSpeaking && Q.Audio.stopSpeaking();
            Q.Audio.pauseAll && Q.Audio.pauseAll();
        }
    },

    stop: function () {
        var tool = this, state = tool.state;
        state._playing = false;
        state._stopped = true;
        state._cursor  = 0;
        // Reset applied flags so NOTEs fire again on next play
        state._notes.forEach(function (n) { n._applied = false; });
        Q.Audio.stopSpeaking && Q.Audio.stopSpeaking();
        var cap  = tool.element.querySelector('.Mpp_caption');
        var play = tool.element.querySelector('.Mpp_play');
        var prog = tool.element.querySelector('.Mpp_prog');
        if (cap)  cap.textContent  = 'Stopped.';
        if (play) play.textContent = '▶ Play';
        if (prog) prog.textContent = '0 / ' + state._cues.length;
    },

    _playFrom: function (idx) {
        var tool  = this;
        var state = tool.state;
        if (!state._playing || state._stopped) return;

        if (idx >= state._cues.length) {
            state._playing = false;
            state._cursor  = 0;
            state._notes.forEach(function (n) { n._applied = false; });
            var cap  = tool.element.querySelector('.Mpp_caption');
            var play = tool.element.querySelector('.Mpp_play');
            var prog = tool.element.querySelector('.Mpp_prog');
            if (cap)  cap.textContent  = 'Finished.';
            if (play) play.textContent = '▶ Play';
            if (prog) prog.textContent = state._cues.length + ' / ' + state._cues.length;
            return;
        }

        state._cursor = idx;
        var cue  = state._cues[idx];
        var cap  = tool.element.querySelector('.Mpp_caption');
        var prog = tool.element.querySelector('.Mpp_prog');

        // Apply NOTEs that fall at or before this cue index
        tool._applyNotesBefore(idx);

        if (state.showCaptions && cap) {
            var controlLabel = cue.control
                ? ' <span style="opacity:.5;font-size:.75em;font-style:normal">[nav]</span>'
                : '';
            cap.innerHTML = cue.speaker
                ? '<strong style="color:var(--AI-accent)">'
                    + _esc(cue.speaker) + ':</strong> '
                    + '<em>' + _esc(cue.text) + '</em>' + controlLabel
                : '<em>' + _esc(cue.text) + '</em>' + controlLabel;
        }
        if (prog) prog.textContent = (idx + 1) + ' / ' + state._cues.length;

        // Navigation cues are shown in captions but not spoken —
        // they were commands, not content to narrate
        if (cue.control) {
            // Advance immediately without speaking
            if (!state._playing || state._stopped) return;
            state._cursor = idx + 1;
            tool._playFrom(state._cursor);
            return;
        }

        tool._narrateCue(cue, function () {
            if (!state._playing || state._stopped) return;
            state._cursor = idx + 1;
            tool._playFrom(state._cursor);
        });
    },

    /**
     * Narrate one cue, call cb when done.
     * Tries pre-generated audio first (Q.Audio instance.play()),
     * falls back to Q.Audio.speak(text, { onEnd: cb }).
     */
    _narrateCue: function (cue, cb) {
        var state = this.state;

        // AI plugin path: pre-generated audio file
        // Q.Audio.collection[url] is a Q.Audio instance with .play() and .onEnded
        if (state.audioBaseUrl && cue.ordinal != null && Q.Audio && Q.Audio.collection) {
            var url    = state.audioBaseUrl + '/cue-' + cue.ordinal + '.mp3';
            var audio  = Q.Audio.collection[url];
            if (audio) {
                // Set onEnded handler keyed by cb so it doesn't accumulate
                audio.onEnded.set(function () {
                    audio.onEnded.remove(cb);
                    cb();
                }, cb);
                audio.play(); // Q.Audio instance method
                return;
            }
        }

        // Base path: Q.Audio.speak with onEnd callback
        // Q.Audio.speak handles voice selection, locale, speechSynthesis cancel/restart
        if (Q.Audio && Q.Audio.speak) {
            Q.Audio.speak(cue.text, {
                locale: state.lang,
                rate:   state.rate,
                pitch:  1,
                volume: 1,
                gender: state.gender || 'female',
                onEnd:  cb
            });
            return;
        }

        // No audio support — advance via setTimeout to avoid deep recursion
        // on long transcripts (each synchronous cb() adds a stack frame)
        setTimeout(cb, 0);
    },

    // ── NOTE application ─────────────────────────────────────────────────

    _applyNotesBefore: function (idx) {
        var tool = this;
        this.state._notes.forEach(function (note) {
            if (note._applied || note.afterCueIndex > idx) return;
            note._applied = true;
            tool._applyNote(note);
        });
    },

    _applyNote: function (note) {
        var state  = this.state;
        var presEl = state.presentationEl;
        var pTool  = presEl && Q.Tool.from(presEl, 'Media/presentation');
        if (!pTool) return;

        var d = note.data || {};
        switch (note.type) {
            case 'Media/presentation/slide':
                if (d.index != null && pTool.goToSlide) {
                    pTool.goToSlide(parseInt(d.index, 10));
                }
                break;
            case 'Media/presentation/card/show':
                if (d.visualizationData && d.streamType) {
                    pTool._showInlineCard(d.streamType, d.visualizationType, d.visualizationData);
                }
                break;
            case 'Media/presentation/graph/update':
                if (d.action && pTool._updateGraph) pTool._updateGraph(d);
                break;
            case 'Media/presentation/table/update':
                if (d.action && pTool._updateTable) pTool._updateTable(d);
                break;
            case 'Media/presentation/tool/show':
                // Generated tool replay — emit event; handler must fetch code from stream
                Q.handle(Q.Media && Q.Media.onPresentationToolShow, pTool,
                    [d.toolName, note.ordinal]);
                break;
        }
    },

    Q: {
        beforeRemove: function () {
            this.state._playing = false;
            this.state._stopped = true;
            Q.Audio.stopSpeaking && Q.Audio.stopSpeaking();
        }
    }
});

// ── Helpers ───────────────────────────────────────────────────────────────────

/**
 * Parse one NOTE line:
 *   "topic from:X to:Y"
 *   "Media/presentation/slide ordinal=45 ts=1748123456 {...json}"
 *   "session_start publisherId=X streamName=Y"
 *
 * @param {String} line
 * @param {Number} afterCueIndex  How many cues appeared before this NOTE
 * @return {Object|null}
 */
function _parseNoteLine(line, afterCueIndex) {
    if (!line) return null;

    // topic NOTE
    if (line.indexOf('topic ') === 0) {
        var fm = line.match(/from:(\S+)/);
        var tm = line.match(/to:(\S+)/);
        return {
            type:           'topic',
            data:           { from: fm ? fm[1] : '', to: tm ? tm[1] : '' },
            afterCueIndex:  afterCueIndex,
            _applied:       false
        };
    }

    // session_start NOTE — extract session origin timestamp
    if (line.indexOf('sessionStart') === 0) {
        var tsm = line.match(/ts=(\d+)/);
        return {
            type:           'sessionStart',
            data:           { ts: tsm ? parseInt(tsm[1], 10) : null },
            afterCueIndex:  0,
            _applied:       false
        };
    }

    // Event NOTEs: type ordinal=N ts=N {...json}
    // Type is everything up to the first space
    var firstSpace = line.indexOf(' ');
    if (firstSpace < 0) return null;
    var type    = line.slice(0, firstSpace);
    var rest    = line.slice(firstSpace + 1);

    var ordinal = null, ts = null, data = {};
    var om = rest.match(/ordinal=(\d+)/);
    if (om) { ordinal = parseInt(om[1], 10); rest = rest.replace(om[0], '').trim(); }
    var tsMatch = rest.match(/ts=(\d+)/);
    if (tsMatch) { ts = parseInt(tsMatch[1], 10); rest = rest.replace(tsMatch[0], '').trim(); }

    // Remaining is the (possibly truncated) JSON instructions
    var jsonStart = rest.indexOf('{');
    if (jsonStart >= 0) {
        try { data = JSON.parse(rest.slice(jsonStart)); } catch (e) {}
    }

    return {
        type:          type,
        ordinal:       ordinal,
        ts:            ts,
        data:          data,
        afterCueIndex: afterCueIndex,
        _applied:      false
    };
}

function _vttSec(timeStr) {
    var parts = timeStr.split(':');
    if (parts.length === 3) {
        return parseFloat(parts[0]) * 3600
             + parseFloat(parts[1]) * 60
             + parseFloat(parts[2]);
    }
    return parseFloat(parts[0]) * 60 + parseFloat(parts[1] || 0);
}

function _esc(str) {
    return String(str)
        .replace(/&/g,'&amp;').replace(/</g,'&lt;')
        .replace(/>/g,'&gt;').replace(/"/g,'&quot;');
}

})(Q, jQuery, window);
